import { NextResponse } from "next/server";
import { db } from "@/lib/db";

// POST /api/seed/test-signals
export async function POST() {
  try {
    const now = new Date();
    const signals = [
      {
        pair: "XAUUSD",
        type: "BUY",
        entry: 2650.5,
        stopLoss: 2645.0,
        takeProfits: JSON.stringify([
          { tp: 2660.0, rr: 1.73 },
          { tp: 2671.1, rr: 3.75 },
          { tp: 2684.41, rr: 6.17 },
        ]),
        confidence: 4,
        status: "ACTIVE",
        signalCategory: "ENTRY",
        rawText: "🟢 إشارة شراء XAUUSD | ENTRY",
        timeframe: "15",
        htfTimeframe: "1س",
        htfTrend: "صاعد",
        smcTrend: "صاعد",
        balance: 1000,
        lotSize: "0.02",
        riskTarget: 10,
        riskPercent: 1,
        actualRisk: 11,
        actualRiskPct: 1.1,
        slDistance: 5.5,
        maxRR: 6.17,
        instrument: "ذهب",
        createdAt: new Date(now.getTime() - 12 * 60000),
      },
      {
        pair: "EURUSD",
        type: "SELL",
        entry: 1.085,
        stopLoss: 1.0875,
        takeProfits: JSON.stringify([
          { tp: 1.082, rr: 1.2 },
          { tp: 1.0795, rr: 2.2 },
        ]),
        confidence: 3,
        status: "ACTIVE",
        signalCategory: "ENTRY",
        rawText: "🔴 إشارة بيع EURUSD | ENTRY",
        timeframe: "5",
        htfTimeframe: "30د",
        htfTrend: "هابط",
        smcTrend: "هابط",
        balance: 2000,
        lotSize: "0.04",
        riskTarget: 20,
        riskPercent: 1,
        actualRisk: 20,
        actualRiskPct: 1,
        slDistance: 25,
        maxRR: 2.2,
        instrument: "عملات",
        createdAt: new Date(now.getTime() - 45 * 60000),
      },
      {
        pair: "GBPUSD",
        type: "BUY",
        entry: 1.272,
        stopLoss: 1.269,
        takeProfits: JSON.stringify([
          { tp: 1.275, rr: 1.0 },
          { tp: 1.278, rr: 2.0 },
          { tp: 1.282, rr: 3.33 },
        ]),
        confidence: 5,
        status: "HIT_TP",
        signalCategory: "TP_HIT",
        rawText: "✅ تحقق الهدف 1 GBPUSD",
        timeframe: "15",
        htfTimeframe: "4س",
        htfTrend: "صاعد",
        smcTrend: "صاعد",
        hitTpIndex: 0,
        hitPrice: 1.275,
        pnlPoints: 30,
        pnlDollars: 30,
        balance: 1500,
        lotSize: "0.1",
        riskTarget: 15,
        riskPercent: 1,
        actualRisk: 15,
        actualRiskPct: 1,
        slDistance: 30,
        maxRR: 3.33,
        instrument: "عملات",
        partialClose: false,
        createdAt: new Date(now.getTime() - 3 * 3600000),
      },
      {
        pair: "XAUUSD",
        type: "SELL",
        entry: 2670.0,
        stopLoss: 2675.5,
        takeProfits: JSON.stringify([
          { tp: 2660.0, rr: 1.82 },
          { tp: 2652.0, rr: 3.27 },
        ]),
        confidence: 3,
        status: "HIT_SL",
        signalCategory: "SL_HIT",
        rawText: "❌ ضرب الوقف XAUUSD",
        timeframe: "15",
        htfTimeframe: "1س",
        htfTrend: "هابط",
        smcTrend: "محايد",
        hitPrice: 2675.5,
        pnlPoints: -55,
        pnlDollars: -11,
        balance: 1000,
        lotSize: "0.02",
        riskTarget: 10,
        riskPercent: 1,
        actualRisk: 11,
        actualRiskPct: 1.1,
        slDistance: 5.5,
        maxRR: 3.27,
        instrument: "ذهب",
        createdAt: new Date(now.getTime() - 5 * 3600000),
      },
      {
        pair: "USDJPY",
        type: "BUY",
        entry: 154.2,
        stopLoss: 153.8,
        takeProfits: JSON.stringify([
          { tp: 154.6, rr: 1.0 },
          { tp: 155.0, rr: 2.0 },
          { tp: 155.6, rr: 3.5 },
        ]),
        confidence: 5,
        status: "ACTIVE",
        signalCategory: "REENTRY",
        rawText: "♻️ صفقة التعويض USDJPY شراء",
        timeframe: "5",
        htfTimeframe: "1س",
        htfTrend: "صاعد",
        smcTrend: "صاعد",
        balance: 1000,
        lotSize: "0.05",
        riskTarget: 10,
        riskPercent: 1,
        actualRisk: 10,
        actualRiskPct: 1,
        slDistance: 40,
        maxRR: 3.5,
        instrument: "عملات",
        createdAt: new Date(now.getTime() - 30 * 60000),
      },
      {
        pair: "USDJPY",
        type: "BUY",
        entry: 154.2,
        stopLoss: 153.8,
        takeProfits: JSON.stringify([]),
        confidence: 0,
        status: "HIT_TP",
        signalCategory: "REENTRY_TP",
        rawText: "♻️ إغلاق كامل بالربح صفقة التعويض USDJPY",
        hitTpIndex: 1,
        hitPrice: 155.0,
        pnlPoints: 80,
        pnlDollars: 40,
        createdAt: new Date(now.getTime() - 2 * 3600000),
      },
      {
        pair: "BTCUSD",
        type: "BUY",
        entry: 104500,
        stopLoss: 103200,
        takeProfits: JSON.stringify([
          { tp: 106000, rr: 1.15 },
          { tp: 108000, rr: 2.62 },
          { tp: 110000, rr: 3.92 },
        ]),
        confidence: 4,
        status: "ACTIVE",
        signalCategory: "PYRAMID",
        rawText: "🔥 تعزيز BTCUSD شراء",
        timeframe: "1س",
        htfTimeframe: "4س",
        htfTrend: "صاعد",
        smcTrend: "صاعد",
        balance: 5000,
        lotSize: "0.01",
        riskTarget: 50,
        riskPercent: 1,
        actualRisk: 52,
        actualRiskPct: 1.04,
        slDistance: 1300,
        maxRR: 3.92,
        instrument: "كريبتو",
        createdAt: new Date(now.getTime() - 90 * 60000),
      },
      {
        pair: "BTCUSD",
        type: "BUY",
        entry: 104500,
        stopLoss: 103200,
        takeProfits: JSON.stringify([]),
        confidence: 0,
        status: "HIT_TP",
        signalCategory: "PYRAMID_TP",
        rawText: "🔥 تعزيز كامل بالربح BTCUSD",
        hitTpIndex: 0,
        hitPrice: 106000,
        pnlPoints: 1500,
        pnlDollars: 15,
        createdAt: new Date(now.getTime() - 1 * 3600000),
      },
    ];

    for (const signal of signals) {
      await db.signal.create({ data: signal });
    }

    return NextResponse.json({
      success: true,
      message: `تم إنشاء ${signals.length} إشارة تجريبية`,
      count: signals.length,
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ success: false, error: "خطأ في إنشاء البيانات التجريبية" }, { status: 500 });
  }
}
